### ISSUE TITLE
setup.cfg configuration support

### ISSUE THREAD

**Issue by sobolevn** [seddonym/layer_linter#15]
Hi, thanks for the awesome tool.

I am thinking about adding it to the https://github.com/wemake-services/wemake-django-template
But, the only feature that it totally required for me is `setup.cfg` support.
Since it it the standard way to configure `python` tools.

I guess it is suitable for the configuration you have to write something like:

```cfg
[tool:layer-lniter]
layers = 
   first
   second

```

How does it sound to you?

**Comment by seddonym** [comment]
Hi @sobolevn,

I hadn't come across `setup.cfg` before, thanks for introducing me to it.

I'd be open to a PR for this, if you wanted to make one.

David

**Comment by seddonym** [comment]
Hi Sobolevn,

You may be interested in my latest project Import Linter, which does everything that Layer Linter does, but has setup.cfg support.

It's in alpha at the moment so probably not suitable for including in a standard template, but take a look!

https://import-linter.readthedocs.io/en/latest/readme.html

**Comment by sobolevn** [comment]
What are the differences between this project and `import-linter`?
Are you looking for collaborators for this new project?

**Comment by sobolevn** [comment]
Clarified in #91. Closing.
