### ISSUE TITLE
Optional layers

### ISSUE THREAD

**Issue by mitchelljkotler** [seddonym/layer_linter#82]
* Layer Linter version: 0.10.3
* Python version: 3.6
* Operating System: Ubuntu

### Description

#74 does the opposite of what I want - I wanted to have layers defined for multiple containers, which will not necessarily all contain all of the layers.  I have downgraded to 0.10.1 for now, as it seems to function how I would like.  Adding syntax for optional layers, or a configuration option, would be helpful.

**Comment by seddonym** [comment]
Thanks so much for the issue report. I'm sorry this has made it necessary for you to downgrade - I will prioritise the optional layer syntax - watch this space!

**Comment by seddonym** [comment]
Optional layers are now possible again with v0.11.0. Just include your optional layers in parentheses (https://layer-linter.readthedocs.io/en/latest/usage.html#additional-syntax).

Let me know if that gives you what you need.

**Comment by mitchelljkotler** [comment]
Thanks!
